version: '3.6'
    
services: 
    # MySQL
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: leanpaydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            
        ports:
            - '3306:3306'

        volumes: 
            - ./init:/docker-entrypoint-initdb.d
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
            
    leanpay-main:
        image: agordic/leanpay_app:0.0.1-SNAPSHOT
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8083:8083
        environment:
            - DATABASE_HOST=db
            - DATABASE_USER=user
            - DATABASE_PASSWORD=user
            - DATABASE_NAME=leanpaydb
            - DATABASE_PORT=3306